window.SUMMARY_EN={
"赫西俄德《神谱》开篇出现的原初存在。":"A primordial being introduced at the opening of Hesiod's Theogony.",
"大地的神格化存在，许多神祇谱系的源头。":"The personification of Earth and the source of many divine genealogies.",
"深渊的神格化存在，同时也是宇宙空间概念。":"The personification of the abyss, also understood as a cosmic realm.",
"在《神谱》中作为早期出现的原初力量之一。":"One of the primordial powers that appears early in the Theogony.",
"幽暗的神格化存在。":"The personification of deep darkness.",
"黑夜女神。":"The goddess of night.",
"天空之神，与盖亚结合产生泰坦等后代。":"The sky god whose union with Gaia produced the Titans and other offspring.",
"海的原初神格。":"The primordial personification of the sea.",
"群山的神格化存在。":"The personified spirits of the mountains.",
"十二泰坦之一。":"One of the twelve Titans.",
"十二泰坦之一，与秩序和神圣法则相关。":"One of the twelve Titans, associated with order and divine law.",
"十二泰坦之一，记忆女神。":"One of the twelve Titans and the goddess of memory.",
"泰坦统治者，宙斯等六位神祇之父。":"Ruler of the Titans and father of Zeus and his five divine siblings.",
"泰坦女神，宙斯等六位神祇之母。":"A Titan goddess and mother of Zeus and his five divine siblings.",
"炉灶与家庭秩序女神。":"Goddess of the hearth and domestic order.",
"农业与丰收女神。":"Goddess of agriculture and the harvest.",
"婚姻女神，宙斯的姐妹与妻子。":"Goddess of marriage, and both sister and wife of Zeus.",
"冥界之王，宙斯与波塞冬的兄弟。":"King of the Underworld and brother of Zeus and Poseidon.",
"海神，宙斯的兄弟。":"God of the sea and brother of Zeus.",
"奥林匹斯众神之王，本原型的中心节点。":"King of the Olympian gods and the central node of this prototype.",
"智慧女神，与雅典娜出生故事密切相关。":"A goddess of wisdom closely connected with Athena's birth story.",
"阿波罗与阿耳忒弥斯之母。":"Mother of Apollo and Artemis.",
"赫尔墨斯之母。":"Mother of Hermes.",
"忒拜公主，狄俄尼索斯之母。":"A Theban princess and mother of Dionysus.",
"珀尔修斯之母。":"Mother of Perseus.",
"赫拉克勒斯之母。":"Mother of Heracles.",
"智慧与战略女神；其出生叙事具有特殊性。":"Goddess of wisdom and strategy, with an extraordinary birth narrative.",
"与音乐、预言、弓术、医药等相关的神。":"A god associated with music, prophecy, archery, medicine, and more.",
"狩猎女神，阿波罗的孪生姐妹。":"Goddess of the hunt and twin sister of Apollo.",
"神使，与旅行、商业、边界等相关。":"Messenger of the gods, associated with travel, commerce, and boundaries.",
"酒、戏剧与狂欢之神。":"God of wine, theater, and ecstatic celebration.",
"宙斯与达那厄之子，斩杀美杜莎的英雄。":"Son of Zeus and Danaë, and the hero who slew Medusa.",
"宙斯与阿尔克墨涅之子，以十二项功业著称。":"Son of Zeus and Alcmene, renowned for his Twelve Labors.",
"战争神，通常视为宙斯与赫拉之子。":"God of war, usually regarded as the son of Zeus and Hera.",
"爱与美的女神；出生谱系存在著名版本差异。":"Goddess of love and beauty, whose birth genealogy has famous variants.",
"火与锻造之神；父系叙事存在版本差异。":"God of fire and metalworking, with variant traditions concerning his father.",
"《伊利亚特》的核心英雄之一。":"One of the central heroes of the Iliad.",
"特洛伊战争叙事的关键人物。":"A key figure in narratives of the Trojan War.",
"特洛伊王子，与海伦及战争起因紧密相关。":"A Trojan prince closely connected with Helen and the origins of the war.",
"迈锡尼王，希腊联军统帅。":"King of Mycenae and commander of the Greek coalition.",
"斯巴达王，海伦的丈夫。":"King of Sparta and husband of Helen.",
"伊萨卡王，《奥德赛》的主人公。":"King of Ithaca and protagonist of the Odyssey.",
"奥德修斯的妻子，以忠贞和智慧著称。":"Wife of Odysseus, celebrated for loyalty and intelligence.",
"忒拜建城者之一，卡德摩斯家族谱系的源头人物。":"A founder of Thebes and ancestral figure of the Cadmean dynasty.",
"卡德摩斯的妻子，与忒拜王族谱系相连。":"Wife of Cadmus and a link in the genealogy of the Theban royal house.",
"卡德摩斯家族后裔，忒拜王统人物。":"A descendant of Cadmus and figure in the Theban royal succession.",
"忒拜王，拉布达科斯家族名祖。":"King of Thebes and eponymous ancestor of the Labdacid dynasty.",
"忒拜王，俄狄浦斯之父。":"King of Thebes and father of Oedipus.",
"拉伊俄斯之妻，俄狄浦斯之母；后与俄狄浦斯成婚。":"Wife of Laius and mother of Oedipus, whom she later married.",
"忒拜王，著名命运悲剧人物。":"King of Thebes and a renowned tragic figure of fate.",
"俄狄浦斯之子，与波吕涅刻斯争夺忒拜王位。":"Son of Oedipus, who contested the Theban throne with Polynices.",
"俄狄浦斯之子，七将攻忒拜传统核心人物之一。":"Son of Oedipus and a central figure in the Seven Against Thebes tradition.",
"俄狄浦斯之女，因埋葬兄长而成为悲剧核心人物。":"Daughter of Oedipus and tragic heroine known for burying her brother.",
"俄狄浦斯之女，安提戈涅之妹。":"Daughter of Oedipus and sister of Antigone.",
"忒拜王族人物，在俄狄浦斯与安提戈涅传统中重要。":"A Theban royal figure important in the traditions of Oedipus and Antigone.",
"克瑞翁之子，安提戈涅的未婚夫。":"Son of Creon and betrothed of Antigone.",
"忒拜著名先知，贯穿多个神话与悲剧传统。":"A famous Theban seer who appears across many myths and tragedies.",
"阿耳戈英雄远征的领袖，为金羊毛前往科尔喀斯。":"Leader of the Argonauts, who sailed to Colchis for the Golden Fleece.",
"科尔喀斯公主与女巫，帮助伊阿宋取得金羊毛。":"A Colchian princess and sorceress who helped Jason obtain the Golden Fleece.",
"科尔喀斯王，美狄亚之父。":"King of Colchis and father of Medea.",
"海洋宁芙，常见传统中为美狄亚之母。":"An Oceanid nymph commonly identified as Medea's mother.",
"伊阿宋之父。":"Father of Jason.",
"伊俄尔科斯王，派伊阿宋寻找金羊毛。":"King of Iolcus, who sent Jason to seek the Golden Fleece.",
"珀利阿斯之子，阿耳戈英雄之一。":"Son of Pelias and one of the Argonauts.",
"著名诗人与乐师，部分传统中为阿耳戈英雄。":"A famous poet and musician, and an Argonaut in some traditions.",
"狄俄斯库里之一，阿耳戈英雄。":"One of the Dioscuri and a member of the Argonauts.",
"阿喀琉斯之父，部分传统中为阿耳戈英雄。":"Father of Achilles and an Argonaut in some traditions.",
"著名女猎手；是否参加阿耳戈远征在传统中有差异。":"A famous huntress whose participation in the Argonaut expedition varies by tradition.",
"守护克里特岛的青铜巨人，在阿耳戈归途中出现。":"A bronze giant guarding Crete who appears during the Argonauts' return.",
"受诸神惩罚的王族祖先人物之一。":"A royal ancestor punished by the gods.",
"伯罗奔尼撒重要王族祖先，阿特柔斯与梯厄斯忒斯之父。":"A major Peloponnesian royal ancestor and father of Atreus and Thyestes.",
"珀罗普斯之妻。":"Wife of Pelops.",
"迈锡尼王，阿伽门农与墨涅拉俄斯之父。":"King of Mycenae and father of Agamemnon and Menelaus.",
"阿特柔斯之弟，与兄长争夺王权。":"Younger brother of Atreus, with whom he contested the kingship.",
"阿特柔斯之妻，阿伽门农与墨涅拉俄斯之母。":"Wife of Atreus and mother of Agamemnon and Menelaus.",
"梯厄斯忒斯之子，与克吕泰涅斯特拉共同杀害阿伽门农。":"Son of Thyestes, who killed Agamemnon together with Clytemnestra.",
"阿伽门农之妻，俄瑞斯忒斯与厄勒克特拉之母。":"Wife of Agamemnon and mother of Orestes and Electra.",
"阿伽门农之子，为父复仇的核心人物。":"Son of Agamemnon and central figure in the revenge for his father.",
"阿伽门农之女，协助俄瑞斯忒斯复仇。":"Daughter of Agamemnon who helped Orestes avenge their father.",
"阿伽门农之女，与奥利斯献祭传统相关。":"Daughter of Agamemnon, associated with the sacrifice at Aulis.",
"阿伽门农与克吕泰涅斯特拉之女。":"Daughter of Agamemnon and Clytemnestra.",
"特洛伊末代国王，赫克托耳与帕里斯之父。":"Last king of Troy and father of Hector and Paris.",
"特洛伊王后，普里阿摩斯之妻。":"Queen of Troy and wife of Priam.",
"特洛伊最重要的战士之一。":"One of Troy's greatest warriors.",
"特洛伊公主与先知。":"A Trojan princess and prophetess.",
"赫克托耳之妻。":"Wife of Hector.",
"海中女神，阿喀琉斯之母。":"A sea goddess and mother of Achilles.",
"阿喀琉斯最亲密的伙伴之一。":"One of Achilles' closest companions.",
"珀尔修斯救出的公主，后成为其妻。":"A princess rescued by Perseus who later became his wife.",
"戈耳工之一，被珀尔修斯斩首。":"One of the Gorgons, beheaded by Perseus.",
"克里特王，与迷宫和米诺陶洛斯传统相连。":"King of Crete, connected with the Labyrinth and Minotaur traditions.",
"雅典英雄，杀死米诺陶洛斯。":"An Athenian hero who killed the Minotaur.",
"米诺斯之女，帮助忒修斯走出迷宫。":"Daughter of Minos who helped Theseus escape the Labyrinth.",
"克里特迷宫中的牛首人身怪物。":"The bull-headed monster of the Cretan Labyrinth.",
"迈锡尼/梯林斯王，命令赫拉克勒斯完成十二功业。":"King of Mycenae or Tiryns who ordered Heracles to perform the Twelve Labors.",
"刀枪难伤的怪狮，为十二功业第一项。":"An invulnerable monstrous lion and the first of the Twelve Labors.",
"勒耳那沼泽中的多头蛇怪。":"The many-headed serpent monster of the Lernaean marsh.",
"阿耳忒弥斯的神圣牝鹿。":"The sacred hind of Artemis.",
"赫拉克勒斯捕获的巨大野猪。":"The giant boar captured by Heracles.",
"厄利斯王，其牛圈成为十二功业之一。":"King of Elis, whose stables became one of the Twelve Labors.",
"居住于斯廷法罗斯湖的凶猛怪鸟。":"Fierce monstrous birds inhabiting Lake Stymphalus.",
"来自克里特的神牛。":"The divine bull from Crete.",
"拥有食人马群的色雷斯国王。":"A Thracian king who owned a herd of man-eating horses.",
"亚马逊女王，其腰带是十二功业目标之一。":"An Amazon queen whose girdle was an object of the Twelve Labors.",
"三身巨人，拥有著名牛群。":"A three-bodied giant who owned a famous herd of cattle.",
"守卫冥界的三头犬。":"The three-headed dog guarding the Underworld.",
"守护金苹果花园的宁芙群体。":"The nymphs who guarded the garden of the golden apples.",
"肩负天空的泰坦，与金苹果功业相关。":"The Titan who bears the sky, associated with the labor of the golden apples.",
"赫拉克勒斯后来的妻子。":"The later wife of Heracles.",
"与赫拉克勒斯和得伊阿尼拉结局相关的半人马。":"A centaur connected with the deaths of Heracles and Deianira.",
"赫拉克勒斯的侄子与重要助手。":"Heracles' nephew and important assistant.",
"阿尔戈斯王，达那厄之父。":"King of Argos and father of Danaë.",
"塞里福斯王，迫使珀尔修斯去取美杜莎首级。":"King of Seriphos who compelled Perseus to obtain Medusa's head.",
"收留达那厄与珀尔修斯的人物。":"The man who sheltered Danaë and Perseus.",
"戈耳工姐妹的亲属，珀尔修斯旅途中遇见。":"Relatives of the Gorgons encountered by Perseus on his journey.",
"有翼神马，与美杜莎死亡神话相关。":"A winged divine horse associated with the myth of Medusa's death.",
"由美杜莎死亡神话产生的人物。":"A figure born from the mythic death of Medusa.",
"安德洛墨达之母。":"Mother of Andromeda.",
"安德洛墨达之父。":"Father of Andromeda.",
"雅典王，忒修斯之父。":"King of Athens and father of Theseus.",
"忒修斯之母。":"Mother of Theseus.",
"米诺斯之妻，米诺陶洛斯之母。":"Wife of Minos and mother of the Minotaur.",
"克里特迷宫的建造者。":"Builder of the Cretan Labyrinth.",
"代达罗斯之子，因飞得过高而坠亡。":"Son of Daedalus, who fell to his death after flying too high.",
"忒修斯赴雅典途中击败的强盗。":"A bandit defeated by Theseus on his journey to Athens.",
"忒修斯早期冒险中击败的强盗。":"A bandit defeated during Theseus' early adventures.",
"米诺斯之女，忒修斯之妻。":"Daughter of Minos and wife of Theseus.",
"忒修斯之子，欧里庇得斯悲剧中的核心人物。":"Son of Theseus and central figure in a tragedy by Euripides.",
"忒拜王，拒绝狄俄尼索斯崇拜而遭毁灭。":"King of Thebes, destroyed after rejecting the worship of Dionysus.",
"彭透斯之母，在狂乱中杀死自己的儿子。":"Mother of Pentheus, whom she killed in a state of divine frenzy.",
"塞墨勒的姐妹，后成为海神勒科忒亚。":"Sister of Semele, later transformed into the sea goddess Leucothea.",
"卡德摩斯之女，阿克泰翁之母。":"Daughter of Cadmus and mother of Actaeon.",
"著名猎人，被变为鹿后遭猎犬撕裂。":"A famous hunter transformed into a stag and torn apart by his own hounds.",
"狄俄尼索斯的年长随从与导师形象。":"An elderly companion and mentor figure of Dionysus.",
"狄俄尼索斯的狂热女性追随者群体。":"The collective of ecstatic female followers of Dionysus.",
"后期狄俄尼索斯传统中的青年伴侣。":"A youthful companion in later Dionysian tradition.",
"俄耳甫斯之妻，其死亡引发冥界寻妻故事。":"Wife of Orpheus, whose death prompted his journey to the Underworld.",
"缪斯之一，常见传统中为俄耳甫斯之母。":"One of the Muses and, in common tradition, mother of Orpheus.",
"色雷斯王，常见传统中为俄耳甫斯之父。":"A Thracian king commonly identified as the father of Orpheus.",
"冥河摆渡人。":"The ferryman of the Underworld river.",
};
